services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: testdb
      MYSQL_USER: utest
      MYSQL_PASSWORD: P@ssw0rd0724
    volumes:
      - ./db_data80:/var/lib/mysql
      - ./db_my80/initialize:/docker-entrypoint-initdb.d
      - ./db_my80/config/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    networks:
      - mysql-network

  mysql_56:
    image: mysql:5.6.51
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: testdb
      MYSQL_USER: utest
      MYSQL_PASSWORD: P@ssw0rd0724
    volumes:
      - ./db_data56:/var/lib/mysql
      - ./db_my56/initialize:/docker-entrypoint-initdb.d
      - ./db_my56/config/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    networks:
      - mysql-network

#  phpmyadmin:
#    image: phpmyadmin
#    depends_on:
#      - mysql
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOSTS=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=mysql
#    ports:
#      - "3001:80"

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Asia/Tokyo'
    volumes:
      - config:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: always

volumes:
  db_data56:
  db_data80:
  config:

networks:
  mysql-network:
    driver: bridge
